parameters:
    gregwar_captcha.controller.class: Gregwar\CaptchaBundle\Controller\CaptchaController
    gregwar_captcha.captcha_type.class: Gregwar\CaptchaBundle\Type\CaptchaType
    gregwar_captcha.captcha_generator.class: Gregwar\CaptchaBundle\Generator\CaptchaGenerator
    gregwar_captcha.image_file_handler.class: Gregwar\CaptchaBundle\Generator\ImageFileHandler
    gregwar_captcha.captcha_builder.class: Gregwar\Captcha\CaptchaBuilder
    gregwar_captcha.phrase_builder.class: Gregwar\Captcha\PhraseBuilder
    
services:
    Gregwar\CaptchaBundle\Controller\CaptchaController:
        public: true
        alias: 'gregwar_captcha.controller'

    gregwar_captcha.controller:
        class: '%gregwar_captcha.controller.class%'
        public: true
        arguments:
            - '@gregwar_captcha.generator'
            - '%gregwar_captcha.config%'
        autowire: true

#    captcha.type:
    gregwar_captcha.type:
        class: '%gregwar_captcha.captcha_type.class%'
        public: true
        arguments:
            - '@session'
            - '@gregwar_captcha.generator'
            - '@translator'
            - '%gregwar_captcha.config%'
        tags:
            - { name: form.type, alias: captcha }

    gregwar_captcha.generator:
        class: '%gregwar_captcha.captcha_generator.class%'
        public: true
        arguments:
            - '@router'
            - '@gregwar_captcha.captcha_builder'
            - '@gregwar_captcha.phrase_builder'
            - '@gregwar_captcha.image_file_handler'

    gregwar_captcha.image_file_handler:
        class: '%gregwar_captcha.image_file_handler.class%'
        public: true
        arguments:
            - '%gregwar_captcha.config.image_folder%'
            - '%gregwar_captcha.config.web_path%'
            - '%gregwar_captcha.config.gc_freq%'
            - '%gregwar_captcha.config.expiration%'

    gregwar_captcha.captcha_builder:
        class: '%gregwar_captcha.captcha_builder.class%'
        public: true

    gregwar_captcha.phrase_builder:
        class: '%gregwar_captcha.phrase_builder.class%'
        public: true
